---
- name: Shell module example
  hosts: all
  tasks:  
  - name: Check system information
    shell: java -version
    register: java_version
  - debug:
        msg: "{{java_version.stdout_lines}}"
